import streamlit as st
from src.pipeline.pipeline import run_research_pipeline
import traceback

st.set_page_config(page_title="AI Research Assistant", page_icon="🤖", layout="wide")

st.title("🤖 LangChain Multi-Agent Research Assistant")
st.write("Enter a topic below, and our AI agents will search the web, read articles, and write a structured report for you!")

topic = st.text_input("Research Topic", placeholder="e.g. Artificial Intelligence in Healthcare")

if st.button("Start Research 🚀", type="primary"):
    if not topic.strip():
        st.warning("Please enter a topic first.")
    else:
        with st.spinner("Agents are researching and drafting your report... This may take a couple of minutes."):
            try:
                # Run the pipeline
                result = run_research_pipeline(topic)
                
                # Display success
                st.success("Research completed successfully!")
                
                # Display Results in Tabs
                tab1, tab2, tab3 = st.tabs(["📄 Final Report", "🧐 Critic Feedback", "🌐 Raw Search Context"])
                
                with tab1:
                    st.markdown(result.get("report", "No report generated."))
                    
                with tab2:
                    st.info("This is the feedback generated by the Critic Chain evaluating the report.")
                    st.markdown(result.get("feedback", "No feedback generated."))
                    
                with tab3:
                    st.write("**Search Results:**")
                    st.text(result.get("search_results", "No search results."))
                    st.write("**Scraped Content Sample:**")
                    scraped = result.get("scraped_content", "")
                    st.text(scraped[:2000] + ("..." if len(scraped) > 2000 else ""))
                    
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")
                with st.expander("Error Details"):
                    st.code(traceback.format_exc())
